/*
 * This source file was generated by the Gradle 'init' task
 */
package uat;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    public static void main(String[] args) {
        // Schedule.startSchedule();

        SpringApplication.run(App.class, args);
    }
}